
logging:
  config: classpath:logback-spring.xml
server:
  port: 8081
spring:
  application:
    name: zns-service-consumer

zns:
  client:
      zk:
        root: /zns
        addr: localhost:2181
        switch: true
      api:
        package: com.buildupchao.zns.service.api
  cluster:
        strategy: Polling